<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_pm1dUOnPEeyJPoXMdyxptw" name="GestaoDoCliente" author="joaop" bonitaVersion="7.14.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_pm1dUenPEeyJPoXMdyxptw" name="Gestão do cliente">
      <elements xmi:type="process:Lane" xmi:id="_pm1dUunPEeyJPoXMdyxptw" name="Equipa de gestão de clientes" actor="_0jLPEOnPEeyJPoXMdyxptw">
        <elements xmi:type="process:Task" xmi:id="_pm1dV-nPEeyJPoXMdyxptw" name="Gerir cliente" outgoing="_E2dQUOnQEeyJPoXMdyxptw" incoming="_2vDQwOnPEeyJPoXMdyxptw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pm1dWOnPEeyJPoXMdyxptw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pm1dWenPEeyJPoXMdyxptw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pm1dWunPEeyJPoXMdyxptw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pm1dW-nPEeyJPoXMdyxptw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pm1dXOnPEeyJPoXMdyxptw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pm1dXenPEeyJPoXMdyxptw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pm1dXunPEeyJPoXMdyxptw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pm1dX-nPEeyJPoXMdyxptw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_pm1dYOnPEeyJPoXMdyxptw">
            <targetForm xmi:type="expression:Expression" xmi:id="_j1eQwOnREeyJPoXMdyxptw" name="GerirCliente" content="9d3f9f24-3be0-4670-b15d-253751266416" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_pm1dYunPEeyJPoXMdyxptw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_pm1dY-nPEeyJPoXMdyxptw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_EZckMOnQEeyJPoXMdyxptw" name="gestão do cliente finalizada" incoming="_E2dQUOnQEeyJPoXMdyxptw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EZckMunQEeyJPoXMdyxptw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EZckMenQEeyJPoXMdyxptw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EZckM-nQEeyJPoXMdyxptw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartMessageEvent" xmi:id="_FdEdAOnTEeyJPoXMdyxptw" name="novo cliente recebido" outgoing="_2vDQwOnPEeyJPoXMdyxptw" event="cliente">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1faN0unPEeyJPoXMdyxptw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1faN0enPEeyJPoXMdyxptw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1faN0-nPEeyJPoXMdyxptw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_tFEM0OnREeyJPoXMdyxptw" name="cliente" dataType="_pm1dgenPEeyJPoXMdyxptw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_tFEM0enREeyJPoXMdyxptw" content=""/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_0Sk8YOnREeyJPoXMdyxptw" name="finalizarProjeto" dataType="_pm1dhOnPEeyJPoXMdyxptw" className="com.company.model.FinalizarProjeto">
        <defaultValue xmi:type="expression:Expression" xmi:id="_0Sk8YenREeyJPoXMdyxptw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_pm1dZOnPEeyJPoXMdyxptw">
        <targetForm xmi:type="expression:Expression" xmi:id="_10ufwOs-EeyxHaVj9Q9pKw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_pm1dZunPEeyJPoXMdyxptw">
        <targetForm xmi:type="expression:Expression" xmi:id="_pm1dZ-nPEeyJPoXMdyxptw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2vDQwOnPEeyJPoXMdyxptw" target="_pm1dV-nPEeyJPoXMdyxptw" source="_FdEdAOnTEeyJPoXMdyxptw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2vDQwenPEeyJPoXMdyxptw"/>
        <condition xmi:type="expression:Expression" xmi:id="_2vDQwunPEeyJPoXMdyxptw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_E2dQUOnQEeyJPoXMdyxptw" target="_EZckMOnQEeyJPoXMdyxptw" source="_pm1dV-nPEeyJPoXMdyxptw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_E2dQUenQEeyJPoXMdyxptw"/>
        <condition xmi:type="expression:Expression" xmi:id="_E2d3YOnQEeyJPoXMdyxptw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_0jLPEOnPEeyJPoXMdyxptw" name="Equipa de gestão de clientes" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_pm1dbOnPEeyJPoXMdyxptw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_pm1dbenPEeyJPoXMdyxptw">
        <name xmi:type="expression:Expression" xmi:id="_pm1dbunPEeyJPoXMdyxptw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pm1db-nPEeyJPoXMdyxptw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_pm1dcOnPEeyJPoXMdyxptw">
        <name xmi:type="expression:Expression" xmi:id="_pm1dcenPEeyJPoXMdyxptw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pm1dcunPEeyJPoXMdyxptw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_pm1dc-nPEeyJPoXMdyxptw">
        <name xmi:type="expression:Expression" xmi:id="_pm1ddOnPEeyJPoXMdyxptw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pm1ddenPEeyJPoXMdyxptw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_pm1ddunPEeyJPoXMdyxptw">
        <name xmi:type="expression:Expression" xmi:id="_pm1dd-nPEeyJPoXMdyxptw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pm1deOnPEeyJPoXMdyxptw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_pm1deenPEeyJPoXMdyxptw">
        <name xmi:type="expression:Expression" xmi:id="_pm1deunPEeyJPoXMdyxptw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_pm1de-nPEeyJPoXMdyxptw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_pm1dfOnPEeyJPoXMdyxptw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_pm1dfenPEeyJPoXMdyxptw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_pm1dfunPEeyJPoXMdyxptw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_pm1df-nPEeyJPoXMdyxptw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_pm1dgOnPEeyJPoXMdyxptw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_pm1dgenPEeyJPoXMdyxptw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_pm1dgunPEeyJPoXMdyxptw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_pm1dg-nPEeyJPoXMdyxptw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_pm1dhOnPEeyJPoXMdyxptw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_pm1dhenPEeyJPoXMdyxptw" type="Process" element="_pm1dUOnPEeyJPoXMdyxptw" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_pm1dhunPEeyJPoXMdyxptw" type="2007" element="_pm1dUenPEeyJPoXMdyxptw">
      <children xmi:type="notation:DecorationNode" xmi:id="_pm1dh-nPEeyJPoXMdyxptw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_pm1diOnPEeyJPoXMdyxptw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_pm1dienPEeyJPoXMdyxptw" type="3007" element="_pm1dUunPEeyJPoXMdyxptw">
          <children xmi:type="notation:DecorationNode" xmi:id="_pm1diunPEeyJPoXMdyxptw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_pm1di-nPEeyJPoXMdyxptw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_pm1djOnPEeyJPoXMdyxptw" type="3005" element="_pm1dV-nPEeyJPoXMdyxptw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pm1djenPEeyJPoXMdyxptw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pm1djunPEeyJPoXMdyxptw" x="213" y="88"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EZckNOnQEeyJPoXMdyxptw" type="3003" element="_EZckMOnQEeyJPoXMdyxptw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_EZdLQOnQEeyJPoXMdyxptw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_EZdLQenQEeyJPoXMdyxptw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EZckNenQEeyJPoXMdyxptw" x="384" y="98"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_FdEdBOnTEeyJPoXMdyxptw" type="3012" element="_FdEdAOnTEeyJPoXMdyxptw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_FdEdBunTEeyJPoXMdyxptw" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_FdEdB-nTEeyJPoXMdyxptw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FdEdBenTEeyJPoXMdyxptw" x="87" y="98" width="30" height="30"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_pm1dk-nPEeyJPoXMdyxptw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_pm1dlOnPEeyJPoXMdyxptw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_pm2rcOnPEeyJPoXMdyxptw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_pm2rcenPEeyJPoXMdyxptw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pm2rcunPEeyJPoXMdyxptw"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_pm2rc-nPEeyJPoXMdyxptw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_pm2rdOnPEeyJPoXMdyxptw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_pm2rdenPEeyJPoXMdyxptw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_pm2rdunPEeyJPoXMdyxptw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pm2rd-nPEeyJPoXMdyxptw" width="800" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_pm2reOnPEeyJPoXMdyxptw"/>
    <edges xmi:type="notation:Connector" xmi:id="_2vDQw-nPEeyJPoXMdyxptw" type="4001" element="_2vDQwOnPEeyJPoXMdyxptw" source="_FdEdBOnTEeyJPoXMdyxptw" target="_pm1djOnPEeyJPoXMdyxptw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2vDQxunPEeyJPoXMdyxptw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2vDQx-nPEeyJPoXMdyxptw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2vDQxOnPEeyJPoXMdyxptw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2vDQxenPEeyJPoXMdyxptw" points="[-2, -8, -106, 0]$[87, -11, -17, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2vFF8OnPEeyJPoXMdyxptw" id="(1.0,0.9333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2vFF8enPEeyJPoXMdyxptw" id="(0.17,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_E2d3YenQEeyJPoXMdyxptw" type="4001" element="_E2dQUOnQEeyJPoXMdyxptw" source="_pm1djOnPEeyJPoXMdyxptw" target="_EZckNOnQEeyJPoXMdyxptw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_E2d3ZOnQEeyJPoXMdyxptw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_E2d3ZenQEeyJPoXMdyxptw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_E2d3YunQEeyJPoXMdyxptw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_E2d3Y-nQEeyJPoXMdyxptw" points="[0, -2, -73, 0]$[69, -2, -4, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E2gToOnQEeyJPoXMdyxptw" id="(1.0,0.64)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_E2gToenQEeyJPoXMdyxptw" id="(0.13333333333333333,0.5)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
